title: ORG Tech Decisions Log
description: Strategic Organization tech decision records.
logo: assets/images/logo.jpg
logo_credit: Image by Markus Winkler from Pixabay

sections:
  - title: Frontend
    description: "Strategic frontend tech decisions."
    posts:
      - strategic-decisions/mobile-tech-stack/index.md
      - strategic-decisions/web-tech-stack/index.md

  - title: Backend
    description: "Strategic backend application tech decisions."
    posts:
      - strategic-decisions/backend-tech-stack-framework/index.md

  - title: Infrastructure
    description: "Strategic infrastructure tech decisions."
    posts:
      - strategic-decisions/infra-tech-stack-aws/index.md
      - strategic-decisions/infra-tech-stack-aws-foundation/index.md
      - strategic-decisions/infra-tech-stack-networking/index.md
      - strategic-decisions/infra-tech-stack-compute/index.md
      - strategic-decisions/infra-tech-stack-messaging/index.md

