#!/usr/bin/env python3
"""Check a Leanpub manuscript's order, Markua anchors, resources and export hashes."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from collections import Counter
from pathlib import Path
from urllib.parse import unquote, urlsplit

from markua import ExportError, links, map_prose, within


def validate_files(files: dict[str, bytes]) -> tuple[list[str], dict]:
    """Validate generated bytes, without requiring a Leanpub account or network."""
    errors: list[str] = []
    order = [line.strip() for line in files.get("Book.txt", b"").decode("utf-8").splitlines()
             if line.strip() and not line.lstrip().startswith("#")]
    if not order:
        errors.append("Book.txt is missing or empty")
    for name, count in Counter(order).items():
        if count > 1:
            errors.append(f"Book.txt lists {name} more than once")
        if name not in files:
            errors.append(f"Book.txt references a missing file: {name}")
    anchors: Counter = Counter()
    internal: list[tuple[str, str]] = []
    used_resources = set()
    directives: list[str] = []
    image_count = 0

    for name in order:
        if name not in files:
            continue
        content = files[name].decode("utf-8")
        if content.startswith("---\n"):
            errors.append(f"{name}: YAML front matter remains")

        def inspect(text: str) -> str:
            nonlocal image_count
            for match in re.finditer(r"\{(?:[^{}\n]*?\bid:\s*|#)([\w-]+)[^{}\n]*\}", text):
                anchor = match[1]
                if not re.fullmatch(r"[A-Za-z][A-Za-z0-9_-]*", anchor):
                    errors.append(f"{name}: invalid Markua id {anchor}")
                anchors[anchor] += 1
            if re.search(r"\[\[[^\]]+\]\]", text):
                errors.append(f"{name}: unresolved journal cross-link")
            if re.search(r"^---(?:begin|end) ", text, re.M):
                errors.append(f"{name}: journal custom block fence remains")
            if re.search(r"</?[A-Za-z][A-Za-z0-9-]*(?:\s[^<>]*|/?)>", text):
                errors.append(f"{name}: raw HTML remains")
            directives.extend(re.findall(r"^\{(mainmatter|backmatter)\}$", text, re.M))
            for link in links(text):
                parsed = urlsplit(link.destination)
                if parsed.scheme or parsed.netloc:
                    if link.image:
                        errors.append(f"{name}: image is not self-contained: {link.destination}")
                    continue
                if not link.image and not parsed.path and parsed.fragment:
                    internal.append((name, unquote(parsed.fragment)))
                    continue
                path = "resources/" + unquote(parsed.path)
                if path not in files:
                    errors.append(f"{name}: missing resource {path}")
                else:
                    used_resources.add(path)
                if link.image:
                    image_count += 1
            return text

        map_prose(content, inspect)
    for anchor, count in anchors.items():
        if count > 1:
            errors.append(f"Duplicate Markua id: {anchor} ({count} occurrences)")
    for name, anchor in internal:
        if anchor not in anchors:
            errors.append(f"{name}: broken internal link #{anchor}")
    if directives not in ([], ["mainmatter"], ["mainmatter", "backmatter"]):
        errors.append(f"Invalid matter directive order: {directives}")
    for path in files:
        if path.startswith("resources/") and path not in used_resources:
            errors.append(f"Unreferenced exported resource: {path}")
    return errors, {"manuscript_files": len(order), "anchors": len(anchors),
                    "internal_links": len(internal), "images": image_count,
                    "resources": len(used_resources),
                    "resource_bytes": sum(len(files[name]) for name in used_resources),
                    "manuscript_bytes": sum(len(data) for data in files.values())}


def validate_directory(directory: Path, source: Path | None = None) -> tuple[list[str], dict]:
    manifest = json.loads(within(directory, "export-manifest.json").read_text(encoding="utf-8"))
    files = {}
    errors = []
    for name, expected in manifest["generated_files"].items():
        path = within(directory, name)
        if not path.is_file():
            errors.append(f"Missing generated file: {name}")
            continue
        data = path.read_bytes()
        files[name] = data
        if hashlib.sha256(data).hexdigest() != expected:
            errors.append(f"Generated file changed since export: {name}")
    found, stats = validate_files(files)
    errors.extend(found)
    actual_order = files.get("Book.txt", b"").decode("utf-8").splitlines()
    if actual_order != manifest.get("book_files"):
        errors.append("Book.txt differs from the export manifest")
    for article in manifest["articles"]:
        if Path(article["source"]).name != "index.md":
            errors.append(f"Non-index article exported: {article['source']}")
        if article["file"] not in actual_order:
            errors.append(f"Article omitted from Book.txt: {article['file']}")
    if source:
        checks = dict(manifest["source_hashes"])
        checks.update({item["source"]: item.get("source_sha256", item["sha256"])
                       for item in manifest["resources"].values()})
        for name, expected in checks.items():
            path = within(source, name)
            if not path.is_file() or hashlib.sha256(path.read_bytes()).hexdigest() != expected:
                errors.append(f"Source changed or missing; rerun export: {name}")
    return errors, stats


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("manuscript", type=Path)
    parser.add_argument("--source", type=Path, help="Also verify the current journal and source artwork")
    parser.add_argument("--max-manuscript-mb", type=float, help="Maximum manuscript size in decimal MB")
    args = parser.parse_args()
    try:
        errors, stats = validate_directory(args.manuscript, args.source)
        if args.max_manuscript_mb is not None:
            if not 0 < args.max_manuscript_mb < float("inf"):
                raise ExportError("--max-manuscript-mb must be a positive finite number")
            if stats["manuscript_bytes"] > args.max_manuscript_mb * 1_000_000:
                errors.append(f"Manuscript exceeds the {args.max_manuscript_mb:g} MB budget")
        if errors:
            for error in errors:
                print(f"[error] {error}", file=sys.stderr)
            return 1
        print("[valid] " + str(args.manuscript))
        print(", ".join(f"{count} {name.replace('_', ' ')}" for name, count in stats.items()
                        if not name.endswith("_bytes")))
        print(f"Resources: {stats['resource_bytes'] / 1_000_000:.2f} MB; "
              f"manuscript total: {stats['manuscript_bytes'] / 1_000_000:.2f} MB")
        return 0
    except (ExportError, OSError, ValueError, KeyError) as error:
        print(f"[error] {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
