title: ADR Templates
description: Templates for architecture decision records (ADRs) and related documentation.
logo: "assets/images/under_the_hood_3.jpg"

sections:
  - title: By People
    description: Templates for architecture decision records (ADRs) and related documentation.
    posts:
      - decision-record-template-by-michael-nygard/index.md
      - decision-record-template-by-gareth-morgan/index.md
      - decision-record-template-by-jeff-tyree-and-art-akerman/index.md
      - decision-record-template-for-alexandrian-pattern/index.md
  - title: By Companies
    description: Templates for architecture decision records (ADRs) and related documentation.
    posts:
      - decision-record-template-by-arc42/index.md
      - decision-record-template-by-edgex/index.md
      - decision-record-template-by-gig-cymru-nhs-wales/index.md
      - decision-record-template-using-planguage/index.md
      - decision-record-template-of-the-madr-project/index.md
  - title: Other
    description:
    posts:
      - decision-record-template-for-business-case/index.md
